Feat: 메인 페이지 구현
rosielsh/my-blog pull request #16
Opened 2023-12-26 16:34 UTC by rosielsh

## 이슈

- #14 

## 작업 사항

- 메인페이지 구현에 필요한 컴포넌트를 구현했습니다.
- react-query를 적용했습니다.
- dummy data를 통해 data fetch까지 완료했습니다. 

## 참고 사항

- 아직 react-query에 대해 학습하고 있는 상태라 올바르게 사용된 것이 아닐 수 있습니다..
-

2023-12-27 04:26 UTC, cheesecat47 requested changes

2023-12-27 09:16 UTC, rosielsh commented on frontend/src/App.tsx
> +                    { path: 'category/:categoryName', element: <PostList /> },
카테고리 전체에 대한 post를 보여주는 페이지입니다! 카테고리 컴포넌트의 가장 위쪽에 있는 카테고리 전체보기 버튼을 누르면 이동하도록 구현할 예정입니다.

2023-12-27 10:28 UTC, cheesecat47 commented on frontend/src/App.tsx
> +                    { path: 'category/:categoryName', element: <PostList /> },
P4: 카테고리 전체에 대한 post라면 전체 글 목록인 것 같은데 url이 category인 이유가 있을까요? 그리고, 전체 글 목록 페이지가 있다면 해당 페이지 내에서 자바스크립트 로직만으로 카테고리 이름으로 필터링하는 것이 속도상으로 빠를 것 같은데 다른 라우팅으로 분리한 이유가 있을까요?

2023-12-28 06:53 UTC, rosielsh commented on frontend/src/App.tsx
> +            { path: 'post/:sort', element: <MainPage /> },
우선 정렬이라는 관점에서 query string을 사용해야 할까 고민했으나, path variable과 query string 방식의 차이점을 찾다가 seo 관점에서 path variable 방식이 더 좋다는 것을 알게 되었습니다.
위의 이유와 더불어 정렬 방식이 여러가지가 아니라 2가지인 점을 고려하여 parameter으로 설계해도 되지 않을까 생각해서 위와같이 사용하였습니다.

path variable 방식이 더 좋은 이유와 관련된 포스팅입니다.
https://velog.io/@timosean/Web-Path-variable-Query-String-%EA%B7%B8%EB%A6%AC%EA%B3%A0-SEO

대충 요약하자면 query string의 값이 변경될 때마다 컨텐츠의 변화가 없어도 중복 컨텐츠로 간주되어 검색 엔진이 실제로 중요한 페이지를 인덱싱하는데 어려움이 생길 수 있다고 합니다.

2023-12-28 06:58 UTC, rosielsh commented on frontend/src/App.tsx
> +            { path: 'post/:sort', element: <MainPage /> },
라우팅은 optional하게 줄 수 있다는 것을 모르고 반복해서 작성했는데, 찾아보니 optional하게 줄 수 있다는 것을 알게되어서 해당 방식으로 수정하여 커밋했습니다 ! ([6eb3279](https://github.com/rosielsh/my-blog/pull/16/commits/6eb32795fd1dbb2b234ba8bbb17056b508ce2b87))

2023-12-28 07:01 UTC, rosielsh commented on frontend/src/components/common/DropBox/DropBox.tsx
> +                    <Menu.Button className="inline-flex w-full justify-center rounded-full border border-ml-pink-200 text-ml-pink-200 px-4 py-2 text-sm font-mediu hover:bg-ml-pink-200 hover:text-whit
수정했습니다! ([ccf0e2b](https://github.com/rosielsh/my-blog/pull/16/commits/ccf0e2b3ab4bdfde94b89a7af9b73e822bffe1fb))

2023-12-28 07:14 UTC, rosielsh commented on frontend/src/App.tsx
> +                    { path: 'category/:categoryName', element: <PostList /> },
일단 위에서 말씀드린 seo 관점에서 path variable을 되도록이면 조금 더 사용해서 page의 의미를 명확히 하자는 의도로 그렇게 작성하기도 했고, 구현 과정에서 다른 블로그 사이트를 참고했는데 해당 부분을 참고한 점도 있습니다 !

필터링은 게시물 개수가 많아질 수록 자바스크립트에서 필터링 로직을 처리하는 것 보다 서버에서 필터링이 된 데이터를 받는 것이 효율적이라고 생각해서 서버에서 data를 받아올 예정입니다.

2023-12-28 07:53 UTC, cheesecat47 approved these changes

2023-12-28 08:33 UTC, merged